version: "3.7"

services:
    alice:
        image: jlesage/firefox
        restart: always
        volumes:
            - /dev/shm:/dev/shm
        ports:
            - "5800:5800"
        networks:
            - mitm
    bob:
        image: aikain/simplehttpserver:0.1
        restart: always
        volumes:
            - ./bob_files:/var/www
        networks:
            - mitm
    eve:
        privileged: true
        build: .
        volumes:
            - ./eve_files:/olicyber
        sysctls:
            # Necessary for transparent mode for mitmproxy
            - net.ipv4.ip_forward=1
            - net.ipv6.conf.all.forwarding=1
            - net.ipv4.conf.all.send_redirects=0
        networks:
            - mitm

networks:
    mitm:
